package dev.wndavenz.music.models

data class SongInfo(
    val title: String,
    val artist: String,
    val album: String,
    val albumArtist: String = "",
    val genre: String = "",
    val year: String = "",
    val trackNumber: String = "",
    val discNumber: String = "",
    val duration: String,
    val composer: String? = null,
    val comment: String? = null,
    val isrc: String? = null,
    val copyright: String? = null,
    val publisher: String? = null,
    val format: String,
    val bitrate: String,
    val sampleRate: String,
    val encoder: String? = null,
    val rgTrackGain: String? = null,
    val rgTrackPeak: String? = null,
    val rgAlbumGain: String? = null,
    val rgAlbumPeak: String? = null,
    val r128Track: String? = null,
    val r128Album: String? = null,
    val loudnessSource: String? = null,
    val appliedGainDb: Double? = null,
    val fileSize: String,
    val filePath: String,
    val fileName: String,
    val folder: String,
    val modified: String? = null,
    val dateAdded: String? = null,
    val hasEmbeddedLyrics: Boolean = false,
    val lyricsType: String? = null,
    val playCount: Int = 0,
)
