name: musicplayer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  glassmorphism_widgets: ^0.2.2
  sticky_headers: ^0.3.0+2
  glassmorphism: ^3.0.0
  palette_generator: ^0.3.3+3
  cached_network_image: ^3.4.1
  just_audio: ^0.9.41
  just_audio_background: ^0.0.1-beta.13
  audio_session: ^0.1.21
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/play_store_512.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/search/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/regular.otf
        - asset: assets/fonts/medium.otf
          weight: 500
        - asset: assets/fonts/bold.otf
          weight: 700
