import 'dart:ui';

import 'flow_field.dart';

/// Produces transform and opacity values for a blurred artwork layer.
class NoiseMotion {
  NoiseMotion({required FlowField flowField}) : this._(flowField);

  const NoiseMotion._(this._flowField);

  final FlowField _flowField;

  /// Generates ambient layer motion. Rendering widgets apply this value only.
  NoiseMotionFrame frameFor({
    required NoiseMotionLayer layer,
    required double timeSeconds,
  }) {
    final sample = _flowField.sample(
      x: layer.fieldX,
      y: layer.fieldY,
      timeSeconds: timeSeconds + layer.timeOffset,
    );
    final companion = _flowField.sample(
      x: layer.fieldX + 23.0,
      y: layer.fieldY - 17.0,
      timeSeconds: (timeSeconds * 0.73) + layer.timeOffset,
    );

    return NoiseMotionFrame(
      translation: Offset(
        (sample.x * layer.translationRadius) +
            (companion.x * layer.translationRadius * 0.34),
        (sample.y * layer.translationRadius * 0.78) +
            (companion.y * layer.translationRadius * 0.28),
      ),
      rotation:
          (sample.rotation * layer.rotationRange) +
          (companion.rotation * layer.rotationRange * 0.32),
      scale:
          layer.baseScale +
          (sample.depth * layer.scaleRange) +
          (companion.depth * layer.scaleRange * 0.38),
      opacity: (layer.baseOpacity + (sample.depth * layer.opacityRange)).clamp(
        layer.minimumOpacity,
        layer.maximumOpacity,
      ),
    );
  }
}

/// Configuration for one procedural background layer.
class NoiseMotionLayer {
  const NoiseMotionLayer({
    required this.fieldX,
    required this.fieldY,
    required this.timeOffset,
    required this.translationRadius,
    required this.rotationRange,
    required this.baseScale,
    required this.scaleRange,
    required this.baseOpacity,
    required this.opacityRange,
    required this.minimumOpacity,
    required this.maximumOpacity,
  });

  /// Deep, slow-moving ambient background layer.
  static const deepBackground = NoiseMotionLayer(
    fieldX: -8.0,
    fieldY: 12.0,
    timeOffset: 0.0,
    translationRadius: 122.0,
    rotationRange: 0.022,
    baseScale: 1.84,
    scaleRange: 0.055,
    baseOpacity: 0.22,
    opacityRange: 0.045,
    minimumOpacity: 0.17,
    maximumOpacity: 0.29,
  );

  /// Lighter foreground fog layer connected to the same flow field.
  static const foregroundFog = NoiseMotionLayer(
    fieldX: 15.0,
    fieldY: -6.0,
    timeOffset: 41.0,
    translationRadius: 72.0,
    rotationRange: 0.017,
    baseScale: 1.43,
    scaleRange: 0.038,
    baseOpacity: 0.88,
    opacityRange: 0.055,
    minimumOpacity: 0.80,
    maximumOpacity: 0.96,
  );

  final double fieldX;
  final double fieldY;
  final double timeOffset;
  final double translationRadius;
  final double rotationRange;
  final double baseScale;
  final double scaleRange;
  final double baseOpacity;
  final double opacityRange;
  final double minimumOpacity;
  final double maximumOpacity;
}

/// Render-ready transform values generated by [NoiseMotion].
class NoiseMotionFrame {
  const NoiseMotionFrame({
    required this.translation,
    required this.rotation,
    required this.scale,
    required this.opacity,
  });

  final Offset translation;
  final double rotation;
  final double scale;
  final double opacity;
}
